### ISSUE TITLE
Snapshot creation fails if directory structures within /var/spool/apt-mirror/mirror attempt to create the same symlink twice

### ISSUE THREAD

**Issue by Vultaire** [majduk/charm-apt-mirror#4]
I've encountered this on a cloud where we're using charm-apt-mirror:

```
2021-09-09 22:55:38 INFO juju-log /var/spool/apt-mirror/mirror/<REDACTED>/apt-mirror/archive.ubuntu.com/ubuntu/pool -> /var/spool/apt-mirror/snapshot-20210909225538//archive.ubu
[...]
2021-09-09 22:57:51 ERROR juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 201, in <module>
    main(AptMirrorCharm)
  File "/var/lib/juju/agents/unit-apt-mirror-0/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-apt-mirror-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-apt-mirror-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-apt-mirror-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-apt-mirror-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 117, in _on_create_snapshot_action
    os.symlink(src_pool, dst_pool)
FileExistsError: [Errno 17] File exists: '/var/spool/apt-mirror/mirror/archive.ubuntu.com/ubuntu/pool' -> '/var/spool/apt-mirror/snapshot-20210909225538/archive.ubuntu.com/ubuntu/pool'
```

This is in an environment where we have one central mirror pulling from upstream, and several secondary mirrors pulling from the central mirror.  It appears that one of the secondary mirrors was at one point pulling from upstream and had a ```/var/spool/apt-mirror/mirror/archive.ubuntu.com/ubuntu``` directory present in addition to the ```/var/spool/apt-mirror/mirror/<REDACTED>/apt-mirror/archive.ubuntu.com/ubuntu``` directory.

It may be necessary to clean up old repository directories in some way to avoid this conflict.

**Comment by Vultaire** [comment]
A workaround: ```rm -r``` any subdirectories in ```/var/spool/apt-mirror/mirror/``` for repos which are no longer being mirrored, or create a ```/var/spool/apt-mirror/mirror.old/``` directory and move the extra subdirectories there instead.
